// Generated by [Toolkit-Py](https://github.com/fujiawei-dev/toolkit-py) Generator
// Created at 2022-03-14 13:53:22.612090, Version 0.12.2

#ifndef IMMIGRATION_OFFICE__CORE_H
#define IMMIGRATION_OFFICE__CORE_H

#endif//IMMIGRATION_OFFICE__CORE_H
