// Generated by [Toolkit-Py](https://github.com/fujiawei-dev/toolkit-py) Generator
// Created at 2022-03-16 10:44:00.927840, Version 0.12.13

import QtQuick 2.12
import QtQuick.Controls 1.5
import QtQuick.Dialogs 1.2
import QtQuick.Window 2.12
import Qt.labs.settings 1.0
import "main.js" as MainJS

Window {
    id: window

    visible: true

    width: 720
    height: 540

    title: qsTr("学生信息表单")

    property bool debugMode: false

    MainForm {
        anchors.fill: parent
        buttonSubmit.onClicked: {				//单击“提交”按钮所要执行的代码
            var hobbyText = "";			//变量用于存放学生兴趣爱好的内容

            for (var i = 0; i < 7; i++) {	//遍历“爱好”组框中的复选框
                /* 生成学生兴趣爱好文本 */
                hobbyText += gridLayoutHobby.children[i].checked ? (gridLayoutHobby.children[i].text + "、") : "";
            }
        
            if (gridLayoutHobby.children[7].checked) {	//若“其他”复选框选中
                hobbyText += "...";
            }
        
            /* 最终生成的完整学生信息 */
            textAreaStudentInfo.text = "我的名字叫" + textFieldName.text + "，是个" + textFieldAge.text + "岁" +
            exclusiveGroupSex.current.text + "生，所学专业是" + comboBoxSpecialty.currentText +
                "，业余喜欢" + hobbyText;

            MainJS.httpPostStudent(textAreaStudentInfo);
        }
    }

    Settings {
        id:settings

        property alias x: window.x
        property alias y: window.y
        property alias width: window.width
        property alias height: window.height
    }

    Component.onCompleted: {
        debugMode = core.debugMode
        if (debugMode){
            MainJS.httpGetExample()
            MainJS.httpPostExample()
        }
    }
}
